### ISSUE TITLE
Exporting to NVM from ply

### ISSUE THREAD

**Issue by Zumbalamambo** [SBCV/Blender-Addon-Photogrammetry-Importer#22]
Thank you for the great addon.

I have got ply file which is the pointcloud, list.txt that has all the image paths, bundler.out file. 

How do I import it into blender and export everything together as nvm file?

**Comment by SBCV** [comment]
I'm afraid this will not work (out of the box) for several reasons.
1.) The addon does currently not support bundler files (I guess the bundler.out file is created with https://github.com/snavely/bundler_sfm)
2.) The addon does ignore the measurements, since this information is currently not used
3.) Since the measurement data is currently not stored as meta data in the blender objects, it can not be written to any output format. 

If you want just convert a bundler.out file to a nvm file, I recommend to directly use some kind of script:
Maybe these python scripts can help you a bit:
https://github.com/SBCV/PythonUtility/blob/master/File_Handler/NVM_File_Handler.py
https://github.com/SBCV/PythonUtility/blob/master/File_Handler/Bundler_File_Handler.py

**Comment by Zumbalamambo** [comment]
@SBCV Thank you!
