### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by unity2k** [SBCV/Blender-Addon-Photogrammetry-Importer#28]
On the newest build you just released it appears you added a couple of new dependencies. They do not load up for me, yes I'm patient :)

In the console on Windows 10 using 2.92 Alpha most recent build, I get the following error: (btw, I ran this as Administrator)

![image](https://user-images.githubusercontent.com/3246704/98296507-43400780-1f70-11eb-839b-b53e93cee6ec.png)

_Edit: just tried this in 2.91 and it works!

2nd Edit: I'm pretty sure this is a Blender 2.92 Alpha issue as the Python Module Manager that was working two days ago is no longer fully functional._

**Comment by SBCV** [comment]
Thank you for reporting this. In the past, the daily builds of Blender have been quite unstable. Thus, I 'm not surprised that it does not work for that specific build :/  
I guess we have to wait until 2.92 is officially released and then we can check again. However, I almost expect that the error will be fixed by then.

**Comment by SBCV** [comment]
Tested with the daily build of today (2.92 Beta) and it works without problems. Feel free to reopen if necessary!
