### ISSUE TITLE
How to Import .PLY through this Addon on Python Script?

### ISSUE THREAD

**Issue by gdosu** [SBCV/Blender-Addon-Photogrammetry-Importer#29]
Hi, first of all, Thank you for developing this great addon.
Unfortunately, I'm new to Blender and Python, So please forgive me for asking basic question.
I'm making simple python script that running blender background and I want import ply file while using this addon.
So I've reading API Reference and I feel totally lost in here.

Is there any function kinda bpy.ops.import_scene.ply? and which module should I import? 

Any recommendation or advice would be appreciated. Many thanks for reading.

**Comment by SBCV** [comment]
Hey, no problem. Do not hesitate to ask.

some general information about using parts of this addon in a python script can be found [here](https://blender-addon-photogrammetry-importer.readthedocs.io/en/latest/python.html).

So in your case, 
- you must install the addon (see [this link](https://blender-addon-photogrammetry-importer.readthedocs.io/en/latest/installation.html#install-the-addon)) and 
- you must install the corresponding dependencies of the addon (see [this link](https://blender-addon-photogrammetry-importer.readthedocs.io/en/latest/installation.html#install-optional-dependencies)), because the `ply-importer` uses the `pyntclound library` to parse the `ply` files.

After installation, I recommend first to try the following from `Blender's python console`. If that works, you can proceed to run this code from some external editor (if required).

```
input_file_path = r'path\to\Blender-Addon-Photogrammetry-Importer\examples\Example.ply'

from photogrammetry_importer.file_handlers.point_data_file_handler import PointDataFileHandler
from photogrammetry_importer.utility.blender_utility import add_collection
from photogrammetry_importer.utility.blender_opengl_utility import draw_points
from photogrammetry_importer.utility.blender_point_utility import add_points_as_particle_system
points = PointDataFileHandler.parse_point_data_file(input_file_path, None)
reconstruction_collection = add_collection("Reconstruction Collection")
```

Option 1: Draw with OpenGL 
```
add_points_to_point_cloud_handle = True
draw_points(None, points, add_points_to_point_cloud_handle, reconstruction_collection)
```

Option 2: Add as particle system
```
mesh_type = "CUBE"
point_extent = 0.01
add_particle_color_emission = True
set_particle_color_flag = False
particle_overwrite_color = (0.0, 1.0, 0.0)
add_points_as_particle_system(None, points, mesh_type, point_extent, add_particle_color_emission, reconstruction_collection, set_particle_color_flag, particle_overwrite_color)
```

I'm afraid that I do not fully understand your use case. Therefore, I can not provide any further guidance at this point. Can you explain a little bit more what you mean with "running blender in the background"?

Does "running Blender in the background" mean 
	- that you want to execute Blender without showing the GUI? 
	- that Blender is already running (with the GUI) and you try to to add the point cloud to an already running Blender process?

Moreover, it would be helpful to know, what you are trying to achieve. Do you want to use the addon to render the point cloud without showing the GUI?

**Comment by SBCV** [comment]
Side note: Blender is currently transitioning from OpenGL to Vulcan and therefore the OpenGL functionality is broken in several recent windows versions

**Comment by gdosu** [comment]
> - that you want to execute Blender without showing the GUI?
Yes. This is what I'm trying.
Thanks for detailed answer. I'll report result asap.

**Comment by gdosu** [comment]
I got some strange error but this is worked anyway

ERROR (bke.bpath): C:\b\buildbot-worker-windows\windows_290\blender.git\source\blender\blenkernel\intern\bpath.c:230 BKE_bpath_relative_convert: basedir='', this is a bug
Info: Saved "result.blend"

Thank you again for awesome answer and addon. Now I can start next process.

**Comment by SBCV** [comment]
If you have another question feel free to reopen / or open a new issue
