### ISSUE TITLE
Do not import .mg

### ISSUE THREAD

**Issue by pseudoua** [SBCV/Blender-Addon-Photogrammetry-Importer#39]
![image](https://user-images.githubusercontent.com/68471179/132360730-69d53f32-af59-46b9-b32a-9afb64e40fd2.png)

**Comment by pseudoua** [comment]
Blender 2.93.4

**Comment by SBCV** [comment]
This "warning" is thrown by the addon, since it detected radial distorted camera parameters in the reconstruction you are importing.
You might want to read [this](https://blender-addon-photogrammetry-importer.readthedocs.io/en/latest/alignment.html). 
In a nutshell: if you have a camera without radial distortion, make sure that during reconstruction

- you are choosing a camera model without radial distortion or
- you are setting the radial distortion to 0

Does that solve your problem?

**Comment by SBCV** [comment]
Have you been able to fix your problem?

**Comment by SBCV** [comment]
Closed due to inactivity - feel free to re-open
