### ISSUE TITLE
point cloud colors

### ISSUE THREAD

**Issue by Tonysa87** [SBCV/Blender-Addon-Photogrammetry-Importer#45]
Hi,

I have just discovered this awesome addon and the point cloud importing phase works just fine, but then, i've some issue accesing the colors for the PC.
I haven't find where the color for each vertex is stored. 

I'm trying this with new Blender 3.1 and the new node Mesh to point.

**Comment by SBCV** [comment]
Hi, I'm afraid I do not fully understand your problem description.

> I have just discovered this awesome addon and the point cloud importing phase works just fine, but then, i've some issue accesing the colors for the PC. I haven't find where the color for each vertex is stored.

Are you trying to read the colors of the point cloud or the of the mesh?
If you are trying to read the colors from a point cloud, then I need to know which point cloud representation did you use. Or in other words: which of the following import option did you select during import:
- "Draw Points in the 3D View with OpenGL"? 
- "Add Points as Particle System"
- "Add Points as Mesh Object"

Is your problem related to [this issue](https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/issues/36)? [Here](https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/commit/8cb5b4f3a55eb18c3c24760c79516459447b71af) is the corresponding commit.

> I'm trying this with new Blender 3.1 and the new node Mesh to point.

Can you share some more information regarding "Mesh to point"? This would help me to understand what you are trying to achieve. Maybe a link or a screenshot would help.

**Comment by enzyme69** [comment]
In the latest Blender, Point Cloud can actually render as spheres, but still needing "Point Info" color, which transfer color data.

But I wonder if your addon also can import the point cloud and save the data as Vertex Color?

**Comment by Tonysa87** [comment]
Sorry to reply so late, i've lost the notification. 

The problem was to assign a material to the point cloud base on actual colors of the single point.

i'm using the option "add points as mesh object" with enabled "add colors as custom propertis", the properties seems to be but there i haven't found a way to transfer  the colors to the actual vertex (or sphere, with the new node "Mesh to point", or just istancing object as points) 

Yes as said by enzume69, blender 3.1 has this new capability to render a point as infinite resolution sphere

**Comment by enzyme69** [comment]
Yes, like I show on my YouTube video, I use SV to transfer the color into Vertex Color. Which is weird and hacky but works for once off thing, since the "Colors" custom props is there:
https://youtu.be/iXvcFQdND-c
<img width="1237" alt="Screen Shot 2022-03-23 at 11 12 59 pm" src="https://user-images.githubusercontent.com/3952687/159696422-1caabb48-ad5f-44f9-a633-d21fc99a525d.png">

Btw, maybe soon Blender can render the point cloud with color spheres via Point Info node, but as for now, it's "Random" only.

**Comment by SBCV** [comment]
I'm afraid that I still don't understand what exactly you are asking for. I should mention that I have no Blender modelling background, so please be **more precise**. Since Blender has so many options/properties, it is difficult to derive what  **what exactly** you are refering to. **A screenshot or a code snippet always helps a lot!**

Where can I find this `Vertex Color` option / property / ... you are refering to? Are you talking about the one which appears if I select a mesh in `3D viewport`, then click in the `properties` area on `Object Data Properties`, then `Vertex Colors`? (See image below).  
![grafik](https://user-images.githubusercontent.com/19491335/160467044-fab15d40-0f1f-4752-b33c-4e9a6412f0d3.png)

If this is what you are asking for, then I'm afraid the answer is: "that is not possible", since this property is not writable from within Python (If I remember correctly).

Maybe we should check, if this is still the case with the current Blender version.

**Comment by SBCV** [comment]
@enzyme69

Thank you for sharing your video. Unfortunately, I'm still struggling to understand what **exactly** you are trying to describe in your video. There are two reasons for this:
a) Your video **obscures** the actual question/problem, since you are covering a lot of topics that are not relevant for the problem
a) switching between multiple blend files / different editor types as well as presenting only the final results (and not the process) makes it hard to derive the connection of the different results (keep in mind that I have only a limited amount of experience with the modeling tools of Blender).

In contrast, I find your screenshot **really** helpful. If you want, we can let the addon create such a node tree by default.

Do you have a simple blend file, which I can use for debugging? That means some blend file that uses the `COLX` attribute (shown in your node tree image) to visualize the point cloud colors in the 3D view. (At the moment I have no idea where to feed the `COLX` attribute to show the colors)

**Comment by Linusnie** [comment]
Hi, I've been working on similar things lately and I think I've found a good solution for adding colors to vertex-instanced objects, which can be displayed in the non-rendered view. Basically these are the steps (full node setup in image below):

- add a `point_color` (or `Col`) color attribute to each vertex 
- add a texture node material that captures the `point_color` attribute
- add a geometry node modifier with a `Set Material` node and pass in the material as a socket of `Group Input` 

All this can be done through scripting, and for more details you can check my recently uploaded plotting addon https://github.com/Linusnie/blender_plots. Getting perfect spheres with colors is also possible (though still only in cycles mode). Maybe something similar could work here?

![Screenshot from 2022-06-21 00-09-18](https://user-images.githubusercontent.com/12471058/174683385-79b7e011-bbbf-4361-9c74-554a4ed65ca0.png)

**Comment by SBCV** [comment]
@Linusnie At first glance this looks like a reasonable approach. I'll check if I find some time, which is currently a bit limited. If you want to provide a PR, I'll be more than happy about it ;) - just let me know.

**Comment by Linusnie** [comment]
@SBCV I've had a look through the code and I think I should be able to add it in without too much trouble, I'll prepare a PR
