### ISSUE TITLE
Render image with blender, view point error

### ISSUE THREAD

**Issue by hwenjun18** [SBCV/Blender-Addon-Photogrammetry-Importer#49]
Hi, I try to use blender to render a new image with colmap sfm result (I use a .obj model ), so I use this addon python interface to import colmap cameras into blender, then I render a image, but the image view is not the same as original image, any idea about this problem?
-------------BTW, I use following api to import and convert camera from colmap to blender
#first import all cameras from colmap folder
cameras, points3D = ColmapFileHandler.parse_colmap_model_folder(model_idp, image_idp, image_fp_type="NAME")

#then add a camera to blender
 camera_object = add_camera_object(cam, cam_name, camera_collection)

then i render with .obj model, but the result image viewpoint is not correct compared with original image

**Comment by SBCV** [comment]
Can you show some example screenshots that illustrate the problem?

**Comment by hwenjun18** [comment]
![image](https://user-images.githubusercontent.com/34371073/168750229-8d4d74c3-b7c0-4d94-a86c-d615ef0ddd14.png)

to be specifically, I use some images to reconstruction a 3D model (.obj format)， then i try to render a image with blender with one image sfm result (colmap format, which is camera [R|T] and  camera intrinsic param). the main purpose for me to use this addon is to convert camera pose from colmap to blender format,

After this, I try to render the viewpoint image with this camera in blender, and i try to compare the render viewpoint with original image, and that seems these two image have different pose as above image shows

**Comment by SBCV** [comment]
I think this is caused by the default parameters of Blender when importing an `obj` file. 
See this code snipped:
 https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/blob/d1e3c732af825b783de2c7e003364c48a55657b0/photogrammetry_importer/importers/mesh_importer.py#L37-L52
 
 You can see that the addon imports the obj file with:
```
 bpy.ops.import_scene.obj(
    filepath=mesh_fp, axis_forward="Y", axis_up="Z"
)
```
BTW: If you import your obj file and the colmap reconstruction, and examine the results in the 3D view, you would see, that the obj file does not align with your point cloud

**Comment by hwenjun18** [comment]
thank you for your reply, I will try again and update my results

**Comment by hwenjun18** [comment]
issue closed, thanks for your solution, it works for me
