### ISSUE TITLE
Show active 3d points per frame?

### ISSUE THREAD

**Issue by noobtoob4lyfe** [SBCV/Blender-Addon-Photogrammetry-Importer#61]
Thanks for sharing this great tool.  
Is there a way easily show only the active 3d points for every frame, meaning just the 3d solved points that are visible and relevant to each frame?  Kind of like how After Effects displays the 3d points in their camera tracker.  I see in the Colmap txt files that get exported that it gives us this information.

**Comment by SBCV** [comment]
This is not possible, since the addon does not read the 2d image features corresponding to the 3D points. Also (depending on the way you want to visualize the point cloud) I do not know, if Blender offers an appropriate (i.e. dynamic) data structure. If not, you would have to copy the modified point cloud multiple times (which is not feasible for large point clouds).

**Comment by noobtoob4lyfe** [comment]
Thanks for your help.  I might be parsing this wrong but, it seems like the exported txt files from colmap should give the info needed in order to my this possible?
![image](https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/assets/43832374/3f16e58f-788a-477b-9a0b-0ace2896058b)

**Comment by SBCV** [comment]
Maybe I misread your question and provided a rather poor answer.
To clarify: The addon (in the current state) does not provide the requested feature, since the addon does not read the 2d features. Reason: the definition of the 2d features differs from library to library - sometimes they are defined w.r.t. the image corner, sometimes to the principal point, ...

If you intend to write your own python script (or extend the addon), this is possible and should not be too difficult. Have a look at the scripting section [here](https://blender-photogrammetry-importer.readthedocs.io/en/latest/index.html).
